# Copyright (c) 2025-2026 Yoran Mertens
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

services:
  pathcov:
    image: sonnyz789123/pathcov-image:2.7.0
    environment:
      - ENV=prod
      - DATA_DIR=${CONTAINER_DATA_DIR}
      - CONFIGS_DIR=${CONTAINER_CONFIGS_DIR}
      - SCRIPTS_DIR=${CONTAINER_SCRIPTS_DIR}
      - SUT_DIR=${CONTAINER_SUT_DIR}
      - DEPS_DIR=${CONTAINER_DEPS_DIR}
      - OUTPUT_DIR=${CONTAINER_OUTPUT_DIR}
    container_name: pathcov
    volumes:
      # - pipeline-data:${CONTAINER_DATA_DIR}
      - ./development/data:${CONTAINER_DATA_DIR}
      - ./pathcov/configs:${CONTAINER_CONFIGS_DIR}:ro
      - ./pathcov/scripts:${CONTAINER_SCRIPTS_DIR}:ro
      - ./output:${CONTAINER_OUTPUT_DIR}
    working_dir: /pathcov-project
    stdin_open: true
    tty: true

  covet-engine:
    image: sonnyz789123/covet-engine-image:4.4.0
    platform: linux/amd64
    environment:
      - ENV=prod
      - DATA_DIR=${CONTAINER_DATA_DIR}
      - CONFIGS_DIR=${CONTAINER_CONFIGS_DIR}
      - SCRIPTS_DIR=${CONTAINER_SCRIPTS_DIR}
      - SUT_DIR=${CONTAINER_SUT_DIR}
      - DEPS_DIR=${CONTAINER_DEPS_DIR}
      - OUTPUT_DIR=${CONTAINER_OUTPUT_DIR}
    container_name: covet-engine
    volumes:
      # - pipeline-data:${CONTAINER_DATA_DIR}
      - ./development/data:${CONTAINER_DATA_DIR}
      - ./covet-engine/configs:${CONTAINER_CONFIGS_DIR}:ro
      - ./output:${CONTAINER_OUTPUT_DIR}
    working_dir: /covet-engine-project
    stdin_open: true
    tty: true

volumes:
  pipeline-data:
