services:
  pathcov:
    image: sonnyz789123/pathcov-image:2.7.0
    environment:
      - ENV=prod
      - DATA_DIR=${CONTAINER_DATA_DIR}
      - CONFIGS_DIR=${CONTAINER_CONFIGS_DIR}
      - SCRIPTS_DIR=${CONTAINER_SCRIPTS_DIR}
      - SUT_DIR=${CONTAINER_SUT_DIR}
      - DEPS_DIR=${CONTAINER_DEPS_DIR}
      - OUTPUT_DIR=${CONTAINER_OUTPUT_DIR}
    container_name: pathcov
    volumes:
      - pipeline-data:${CONTAINER_DATA_DIR}
      - ./pathcov/configs:${CONTAINER_CONFIGS_DIR}:ro
      - ./pathcov/scripts:${CONTAINER_SCRIPTS_DIR}:ro
      - ./output:${CONTAINER_OUTPUT_DIR}
    working_dir: /pathcov-project
    stdin_open: true
    tty: true

  covet-engine:
    image: sonnyz789123/covet-engine-image:4.4.0
    platform: linux/amd64
    environment:
      - ENV=prod
      - DATA_DIR=${CONTAINER_DATA_DIR}
      - CONFIGS_DIR=${CONTAINER_CONFIGS_DIR}
      - SCRIPTS_DIR=${CONTAINER_SCRIPTS_DIR}
      - SUT_DIR=${CONTAINER_SUT_DIR}
      - DEPS_DIR=${CONTAINER_DEPS_DIR}
      - OUTPUT_DIR=${CONTAINER_OUTPUT_DIR}
    container_name: covet-engine
    volumes:
      - pipeline-data:${CONTAINER_DATA_DIR}
      - ./jdart/configs:${CONTAINER_CONFIGS_DIR}:ro
      - ./covet-engine/configs:${CONTAINER_CONFIGS_DIR}:ro
      - ./output:${CONTAINER_OUTPUT_DIR}
    working_dir: /covet-engine-project
    stdin_open: true
    tty: true

volumes:
  pipeline-data:
