# Copyright (c) 2025-2026 Yoran Mertens
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

FROM sonnyz789123/pathcov-image:latest

LABEL maintainer="yoranmertens0@gmail.com"

###############################################################################
# Install system dependencies
###############################################################################
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        maven \
        git \
        ca-certificates \
        bash && \
    rm -rf /var/lib/apt/lists/*

###############################################################################
# Project directory
###############################################################################
ENV PATHCOV_PROJECT_DIR=/pathcov-project
RUN mkdir -p ${PATHCOV_PROJECT_DIR}

###############################################################################
# Install SootUp
###############################################################################
ENV SOOTUP_VERSION=2.0.1
WORKDIR ${PATHCOV_PROJECT_DIR}
RUN git clone --branch v${SOOTUP_VERSION} https://github.com/SonnyZ789123/SootUp.git
WORKDIR ${PATHCOV_PROJECT_DIR}/SootUp
RUN git checkout v${SOOTUP_VERSION}
RUN mvn -B clean install -DskipTests

###############################################################################
# Install intellij-coverage-model
###############################################################################
ENV INTELLIJ_COVERAGE_MODEL_VERSION=3.1.0
WORKDIR ${PATHCOV_PROJECT_DIR}
RUN git clone --branch v${INTELLIJ_COVERAGE_MODEL_VERSION} https://github.com/SonnyZ789123/intellij-coverage-model.git
WORKDIR ${PATHCOV_PROJECT_DIR}/intellij-coverage-model
RUN git checkout v${INTELLIJ_COVERAGE_MODEL_VERSION}
RUN mvn -B clean install -DskipTests

ENV COVERAGE_MODEL_JAR=${PATHCOV_PROJECT_DIR}/intellij-coverage-model/target/intellij-coverage-model-${INTELLIJ_COVERAGE_MODEL_VERSION}.jar

###############################################################################
# Install pathcov
###############################################################################
# PATHCOV_VERSION is inherited from the base image, but we need to build it from source for development
WORKDIR ${PATHCOV_PROJECT_DIR}
RUN git clone --branch v${PATHCOV_VERSION} https://github.com/SonnyZ789123/pathcov.git
WORKDIR ${PATHCOV_PROJECT_DIR}/pathcov
RUN git checkout v${PATHCOV_VERSION}
# Skip the shading to keep dependencies separate for development
RUN mvn -B clean install -DskipTests -DskipShade 

# Override the PATHCOV_JAR set in prod image which was the fat jar
ENV PATHCOV_JAR=${PATHCOV_PROJECT_DIR}/pathcov/target/pathcov-${PATHCOV_VERSION}.jar

###############################################################################
# Default
###############################################################################
WORKDIR ${PATHCOV_PROJECT_DIR}
CMD ["/bin/bash"]
