# Copyright (c) 2025-2026 Yoran Mertens
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# ============================================================
# SUT configuration
# ============================================================
sut:
  # Paths should be relative to the root given in the .env file
  compiled_root: target/classes
  test_root: target/test-classes
  source_root: src/main/java
  # Optional test_deps_classpath: specify the classpath for the dependencies (colon-separated, test scope)
  # The paths should be absolute and be in the DEPS_DIR if defined in the .env
  # if not specified, it will be auto-detected from the SUT_DIR, and should be in the DEPS_DIR if defined in the .env
  # test_deps_classpath:

  # Optional runtime_deps_classpath: specify the classpath for the dependencies (colon-separated, runtime scope)
  # The paths should be absolute and be in the DEPS_DIR if defined in the .env
  # if not specified, it will be auto-detected from the SUT_DIR, and should be in the DEPS_DIR if defined in the .env
  # runtime_deps_classpath:

  # Optional junit_options: specify junit run options (e.g., --select-class com.example.MyTestClass)
  # if not specified, --scan-classpath will be used
  junit_options: --select-class com.thealgorithms.maths.LongDivisionTest

test_generation:
  # Optional generated_tests_dir_out: specify the output directory for generated tests, relative to the SUT_DIR
  # if not specified, it will default to "generated-tests" in the OUTPUT_dir
  # generated_tests_dir_out: 
entry:
  class: vm.Main

target:
  class: com.thealgorithms.maths.LongDivision
  method: divide
  return: int
  parameters:
    - name: dividend
      type: int
    - name: divisor
      type: int

analysis:
  project_prefixes:
    - com.thealgorithms.maths
